### Internal Spring Configuration
#server:
#  servlet:
#    context-path: "/server"
spring:
  servlet:
    multipart.max-file-size: 100MB
    multipart.max-request-size: 100MB
  datasource:
    url: "jdbc:h2:file:./allure/db"
    # H2 default username
    username: sa
    # H2 default password (empty)
    password:
  jpa:
    database: H2
    show-sql: false
    hibernate.ddl-auto: update

vaadin.urlMapping: "/ui/*"
server.port: ${PORT:8080}
### Security
basic.auth:
  username: admin
  password: admin
  enable: false
### App Configuration
springdoc.swagger-ui.path: /swagger-ui.html

# #################
# Deprecated format. Not supported!
# #################
# allure:
#   results.dir: allure/results/
#   reports:
#     dir: allure/reports/
#     path: reports/
#     history.level: 20
#   support.old.format: false
#   date.format: "yy/MM/dd HH:mm:ss"

allure:
  resultsDir: allure/results/
  reports:
    dir: allure/reports/
    path: reports/
    history-level: 20
  support-old-format: false
  date-format: "yy/MM/dd HH:mm:ss"
  clean:
    dryRun: false
    time: "00:00"
    ageDays: 90
    paths:
      - path: "manual_uploaded"
        ageDays: 30
  server-base-url:
logging:
  level:
    root: INFO
    org.atmosphere: WARN # Vaadin (GUI) Server
    org.springframework: INFO
    org.springframework.core: WARN
    org.springframework.beans.factory.support: WARN
    ru.iopump.qa:allure: INFO # Allure Server Logs